// Generated by Fair on 2021-03-04 17:18:37.974136.
import 'package:fair_example/src/utils/form/form_field_builder.dart';
import 'package:fair_example/src/utils/form/form_builder_custom_field.dart';
import 'package:fair_example/src/utils/form/form_builder.dart';
import 'package:smooth_star_rating/smooth_star_rating.dart';

import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

import 'pages/news/widget/list_container.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'FormBuilderCustomField': (props) => FormBuilderCustomField(
            key: props['key'],
            attribute: props['attribute'],
            formField: props['formField'],
            validators: props['validators'] ?? const [],
            valueTransformer: props['valueTransformer'],
            initialValue: props['initialValue'],
          ),
      'ListContainer': (props) => ListContainer(
            props['pa'][0],
          ),
      'FormBuilder': (props) => FormBuilder(
            key: props['key'],
            child: props['child'],
            readOnly: props['readOnly'] ?? false,
            onChanged: props['onChanged'],
            autovalidate: props['autovalidate'] ?? false,
            onWillPop: props['onWillPop'],
            showValidateStyle: props['showValidateStyle'] ?? true,
            initialValue: props['initialValue'] ?? const {},
          ),
      'TextFormFieldBuilder': (props) => TextFormFieldBuilder(
            key: props['key'],
            attribute: props['attribute'],
            onChange: props['onChange'],
          ),
      'SmoothStarRating': (props) => SmoothStarRating(
            starCount: props['starCount'] ?? 5,
            isReadOnly: props['isReadOnly'] ?? false,
            spacing: props['spacing']?.toDouble() ?? 0.0,
            rating: props['rating']?.toDouble() ?? 0.0,
            defaultIconData: props['defaultIconData'] ?? Icons.star_border,
            onRated: props['onRated'],
            color: props['color'],
            borderColor: props['borderColor'],
            size: props['size']?.toDouble() ?? 25,
            filledIconData: props['filledIconData'] ?? Icons.star,
            halfFilledIconData: props['halfFilledIconData'] ?? Icons.star_half,
            allowHalfRating: props['allowHalfRating'] ?? true,
          ),
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'FormBuilder': true,
      'FormBuilderCustomField': true,
      'ListContainer': true,
      'SmoothStarRating': true,
      'TextFormFieldBuilder': true,
    };
  }
}
