// Generated by Fair on 2021-02-26 17:16:19.902900.

import 'package:fair_example/src/pages/news/widget/list_container.dart';
import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'ListContainer': (props) => ListContainer(
            props['pa'][0],
          ),
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'ListContainer': true,
    };
  }
}
